package mbci.oracle.apps.xxmb.rice183.server;

import oracle.apps.fnd.framework.server.OAViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ReqHdrVOImpl extends OAViewObjectImpl {
    /**This is the default constructor (do not remove)
     */
    public ReqHdrVOImpl() {
    }

    /**Gets the bind variable value for pQueryID
     */
    public String getpQueryID() {
        return (String)getNamedWhereClauseParam("pQueryID");
    }

    /**Sets <code>value</code> for bind variable pQueryID
     */
    public void setpQueryID(String value) {
        setNamedWhereClauseParam("pQueryID", value);
    }
}
